[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "TGIF"
version = "1.0.5"

dependencies = [
    "numpy",
    "scipy",
    "astropy",
    "matplotlib",
    "pandas"]
